Fix ZEO cache tracing wrt 2038 year
@bmwiedemann reports that ZEO tests fail in year 2038. From
https://github.com/zopefoundation/ZEO/issues/245:

    Failure in test cache_simul_properly_handles_load_miss_after_eviction_and_inval (ZEO.tests.test_cache)
    Failed doctest test for ZEO.tests.test_cache.cache_simul_properly_handles_load_miss_after_eviction_and_inval
      File "/home/abuild/rpmbuild/BUILD/python-ZEO-6.1-build/zeo-6.1/src/ZEO/tests/test_cache.py", line 1015, in cache_simul_properly_handles_load_miss_after_eviction_and_inval

    ----------------------------------------------------------------------
    File "/home/abuild/rpmbuild/BUILD/python-ZEO-6.1-build/zeo-6.1/src/ZEO/tests/test_cache.py", line 1021, in ZEO.tests.test_cache.cache_simul_properly_handles_load_miss_after_eviction_and_inval
    Failed example:
        cache = ZEO.cache.ClientCache('cache', 1<<21)
    Exception raised:
        Traceback (most recent call last):
          File "/usr/lib64/python3.11/doctest.py", line 1355, in __run
            exec(compile(example.source, filename, "single",
          File "<doctest ZEO.tests.test_cache.cache_simul_properly_handles_load_miss_after_eviction_and_inval[1]>", line 1, in <module>
            cache = ZEO.cache.ClientCache('cache', 1<<21)
          File "/home/abuild/rpmbuild/BUILD/python-ZEO-6.1-build/zeo-6.1/src/ZEO/cache.py", line 239, in __init__
            self._setup_trace(path)
          File "/home/abuild/rpmbuild/BUILD/python-ZEO-6.1-build/zeo-6.1/src/ZEO/cache.py", line 823, in _setup_trace
            _trace(0x00)
          File "/home/abuild/rpmbuild/BUILD/python-ZEO-6.1-build/zeo-6.1/src/ZEO/cache.py", line 814, in _trace
            pack(">iiH8s8s",
        struct.error: 'i' format requires -2147483648 <= number <= 2147483647

Unfortunately as ZEO/scripts/cache_stats.py and ZEO/scripts/cache_simul.py show
ZEO cache-trace files do not have header nor magic, so we cannot change format
of time field from 32-bit integer to 64-bit integer without backward
compatibility breakage. But there is a hack: we can change the format from
32-bit signed int to 32-bit unsigned int and gain support till 2106 in backward
compatible manner:

    In [11]: time.ctime((1 << 32) - 1)
    Out[11]: 'Sun Feb  7 09:28:15 2106'

    In [12]: time.ctime((1 << 31) - 1)
    Out[12]: 'Tue Jan 19 06:14:07 2038'

-> Do that to keep binary compatibility and give us another 70 years to find a
proper solution similarly to how mariadb did it.

/reported-and-helped-by @bmwiedemann
/reviewed-by @perrinjerome, @dataflake, @bmwiedemann
/reviewed-on https://github.com/zopefoundation/ZEO/pull/246
/fixes https://github.com/zopefoundation/ZEO/issues/245